version: '3.7'

services:
  openvino-devkit:
    image: ruhyadi/openvino:v2022.2.0
    user: root
    stdin_open: true
    tty: true
    volumes:
      - ./:/opt/intel/openvino/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/tmp/.docker.xauth
      - QT_X11_NO_MITSHM=1